parent: ./conf/hierarchical_attention/word_char_blstm_nested_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  encoder_num_layers_sub: 5
  subsample_list:
    - False
    - True
    - True
    - True
    - False
  decoding_order: bahdanau
  num_heads: 1

  # optimization
  batch_size: 50

  # initialization
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/character_wb/all/blstm320H5L_drop4_fc_320_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
  ctc_loss_weight_sub: 0

  # W2C attention
  usage_dec_sub: all
  logits_injection: False
  num_heads_dec: 1
  dec_attention_type: content

  # regularization
  dec_attend_temperature: 1
  dec_sigmoid_smoothing: True
  att_reg_weight: 0
  relax_context_vec_dec: False
  gating: False
