parent: ./conf/hierarchical_attention/word_char_blstm_hie_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: aps_other
  label_type: word10k
  label_type_sub: character

  # topology
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  activation: relu
  batch_norm: True
  encoder_bidirectional: True
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 3
  encoder_num_layers_sub: 2
  subsample_list:
    - False
    - True
    - False

  # optimization
  batch_size: 25

  # initialization
  pretrained_model_path: False

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
  ctc_loss_weight_sub: 0

  # RNNLM fusion
  rnnlm_fusion_type: False
  rnnlm_path: False
  rnnlm_path_sub: False
  rnnlm_weight: 0
  rnnlm_weight_sub: 0
