parent: ./conf/hierarchical_attention/word_char_blstm_hie_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all
  vocab: False
  # vocab: aps_other
  label_type: word10k
  label_type_sub: character

  # topology
  encoder_num_layers: 5
  encoder_num_layers_sub: 4
  subsample_list:
    - True
    - True
    - False
    - True
    - False

  # optimization
  batch_size: 40

  # initialization
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/character/all/blstm320H5L_drop12_fc_320_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
  ctc_loss_weight_sub: 0

  # RNNLM fusion
  rnnlm_fusion_type: False
  rnnlm_path: False
  rnnlm_path_sub: False
  rnnlm_weight: 0
  rnnlm_weight_sub: 0
