parent: ./conf/rnnlm/word_lstm_rnnlm_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all
  vocab: aps_other
  # label_type: word1k
  # label_type: word5k
  label_type: word10k
  # label_type: word15k
  # label_type: word20k
  # label_type: word25k

  # topology
  model_type: rnnlm
  rnn_type: lstm
  bidirectional: False
  num_units: 512
  num_proj: 0
  num_layers: 2
  embedding_dim: 512
  tie_weights: True
  residual_connection: True
  backward: False

  # optimization
  batch_size: 256
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 50
  convert_to_sgd_epoch: 40
  bptt: 100

  # annealing
  print_step: 200
