parent: ./conf/rnnlm/word_lstm_rnnlm_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all
  # vocab: False
  vocab: aps_other
  label_type: word

  # topology
  model_type: rnnlm
  rnn_type: lstm
  bidirectional: False
  num_units: 512
  num_proj: 0
  num_layers: 2
  embedding_dim: 128
  tie_weights: False
  residual_connection: True
  backward: False

  # optimization
  batch_size: 128
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 70
  convert_to_sgd_epoch: 10
  bptt: 35

  # annealing
  print_step: 200
