parent: ../config/ctc/word/blstm_ctc_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: kanji
  num_classes: 2888

  # topology
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3

  # annealing
  print_step: 500
