parent: ./conf/attention/char_blstm_att_train_si284.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: train_si284
  label_type: word

  # topology
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  activation: relu
  batch_norm: True
  encoder_bidirectional: True
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False
  attention_dim: 128
  decoder_num_units: 256
  embedding_dim: 128
  decoding_order: bahdanau
  bottleneck_dim: 256
  num_heads: 1

  # optimization
  batch_size: 20

  # initialization
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/wsj/pytorch/ctc/character/train_si284/conv_64_64_128_128_blstm256H4L_bn_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 40000

  # annealing
  print_step: 200

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0

  # RNNLM fusion
  rnnlm_fusion_type: False
  rnnlm_path: False
  rnnlm_joint_training: False
  rnnlm_weight: 0
  concat_embedding: False
