### topology
n_splices: 1
n_stacks: 1
n_skips: 1
max_n_frames: 2000
sequence_summary_network: false
conv_in_channel: 1
conv_channels: "64"
conv_kernel_sizes: "(3,3)"
conv_strides: "(2,2)"
conv_poolings: "(1,1)"
conv_batch_norm: false
conv_residual: false
conv_bottleneck_dim: 0
enc_type: conv_transformer
dec_type: transformer
enc_n_layers: 12
dec_n_layers: 6
attn_type: scaled_dot
pe_type: add
d_model: 256
d_ff: 2048
attn_n_heads: 4
tie_embedding: false
ctc_fc_list: "512"
### optimization
batch_size: 40
optimizer: adam
learning_rate_factor: 2
n_epochs: 100
convert_to_sgd_epoch: 100
print_step: 200
metric: edit_distance
sort_stop_epoch: 100
not_improved_patient_n_epochs: 5
eval_start_epoch: 10
warmup_n_steps: 8000
accum_grad_n_tokens: 0
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.2
dropout_dec: 0.2
dropout_emb: 0.1
dropout_att: 0.2
weight_decay: 1e-6
lsm_prob: 0.1
focal_loss: 0.0
adaptive_softmax: false
# SpecAugment
freq_width: 27
n_freq_masks: 0
time_width: 70
n_time_masks: 0
time_width_upper: 0.2
### MTL
ctc_weight: 0.0
ctc_lsm_prob: 0.1
bwd_weight: 0.0
mtl_per_batch: true
task_specific_layer: false
