param:
  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  save_format: numpy
  input_channel: 41
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 2
  num_skip: 2

  # topology
  model_type: ctc
  encoder_type: lstm
  bidirectional: True
  residual: False
  dense_residual: False
  num_units: 256
  num_proj: 0
  num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  fc_list: []
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  batch_norm: False

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100
  convert_to_sgd_epoch: 100

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.5
  weight_decay: 0
  logits_temperature: 1
  label_smoothing_prob: 0
  weight_noise_std: 1e-5

  # annealing
  decay_start_epoch: 20
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 20
  print_step: 10
