param:
  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  save_format: numpy
  input_size: 123
  splice: 1
  num_stack: 2
  num_skip: 2

  # topology
  model_type: ctc
  encoder_type: lstm
  bidirectional: True
  num_units: 256
  num_proj: 0
  num_layers: 5
  bottleneck_dim_list: []
  channels: []
  kernel_sizes: []
  strides: []
  batch_norm: False

  # optimization
  batch_size: 50
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.5
  weight_decay: 0
  logits_temperature: 1
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 20
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 20
  not_improved_patient_epoch: 10
  eval_start_epoch: 20
  print_step: 10
