param:
  # framework
  framework: pytorch
  
  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  save_format: numpy
  input_channel: 41
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 1
  num_skip: 1

  # topology
  model_type: ctc
  encoder_type: cnn
  bidirectional: False
  residual: False
  dense_residual: False
  num_units: 0
  num_proj: 0
  num_layers: 0
  subsample_list:
    - False
  fc_list: [1024, 1024, 1024]
  conv_channels: [128, 128, 128, 128, 256, 256, 256, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  conv_strides:
    - [1, 2]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - [3, 1]
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  # activation: relu
  activation: prelu
  # activation: hard_tanh
  # activation: maxout
  batch_norm: True

  # optimization
  batch_size: 10
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 200
  convert_to_sgd_epoch: 200

  # regularization
  parameter_init: 0.05
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.3
  weight_decay: 1e-5
  logits_temperature: 1
  label_smoothing_prob: 0
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 20
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 20
  print_step: 100
