param:
  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  save_format: numpy
  input_size: 123
  splice: 11
  num_stack: 1
  num_skip: 1

  # topology
  model_type: ctc
  encoder_type: cnn
  bidirectional: True
  num_units: 0
  num_proj: 0
  num_layers: 0
  bottleneck_dim_list: [1024, 1024, 1024]
  channels:
    - 128
    - 128
    - 128
    - 128
    - 256
    - 256
    - 256
    - 256
    - 256
    - 256
  kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  pooling:
    - [1, 3, 1]  # 1st layer, (freq,time) = (3,1)
  batch_norm: False

  # optimization
  batch_size: 20
  optimizer: adam
  learning_rate: 1e-4
  num_epoch: 100

  # regularization
  parameter_init: 0.05
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.3
  weight_decay: 0
  logits_temperature: 1
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 20
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 20
  print_step: 10
