parent: ../config/ctc/word/blstm_ctc_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  data_size: fullset
  num_classes: 23178

  # features
  num_stack: 1
  num_skip: 1

  # topology
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 64

  # annealing
  print_step: 1000
