parent: ../config/hierarchical_attention/att_word_freq5_att_kanji_subset.yml
param:
  # framework
  backend: chainer

  attention_type: content

  batch_size: 128
  scheduled_sampling_ramp_max_step: 125000
  print_step: 500

  # batch_size: 64
  # scheduled_sampling_ramp_max_step: 250000
  # print_step: 1000

  # MTL
  main_loss_weight: 0.8
  ctc_loss_weight_sub: 0.2
