param:
  # model: blstm_attention
  corpus: timit
  label_type: phone61
  feature: fbank
  input_size: 120
  splice: 1
  num_stack: 1
  num_skip: 1
  encoder_type: gru
  encoder_bidirectional: True
  encoder_num_units: 256
  # encoder_num_proj: 256
  encoder_num_layers: 4
  encoder_dropout: 0.1
  attention_type: content
  attention_dim: 128
  sharpening_factor: 1
  decoder_type: gru
  decoder_num_units: 256
  # decoder_num_proj: 256
  # decoder_num_layers: 1
  decoder_dropout: 0.1
  embedding_dim: 64
  logits_tempareture: 1
  max_decode_length: 100

  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  decay_start_epoch: 20
  decay_rate: 0.5
  decay_patient_epoch: 3
  num_epoch: 50
  parameter_init: 0.1
  clip_grad_norm: 5.0
  weight_decay: 0
  eval_start_epoch: 10
  print_step: 10
  beam_width: 20
  # sort_stop_epoch: 20
