parent: ../config/attention/att_bgru.yml
param:
  # framework
  backend: chainer

  attention_type: content
  # attention_type: location

  # initialization
  recurrent_weight_orthogonal: False

  # MTL
  ctc_loss_weight: 0
  # ctc_loss_weight: 0.2

  batch_size: 40
  scheduled_sampling_ramp_max_step: 6400
  print_step: 10
