parent: ../config/ctc/blstm_ctc.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  num_layers: 5
  subsample_list:
    - False
    - True
    - False
    - False
    - False
