parent: ../config/attention/att_bgru.yml
param:
  # framework
  backend: chainer

  attention_type: content

  # initialization
  recurrent_weight_orthogonal: False

  # MTL
  ctc_loss_weight: 0
  # ctc_loss_weight: 0.2
