param:
  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  save_format: numpy
  input_channel: 41
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 1
  num_skip: 1

  # topology
  model_type: attention
  encoder_type: gru
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  decoder_residual: False
  decoder_dense_residual: False
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False
  attention_type: location
  attention_dim: 128
  decoder_type: gru
  decoder_num_units: 256
  decoder_num_layers: 1
  embedding_dim: 256
  attention_conv_num_channels: 10
  attention_conv_width: 101

  # CNN before RNN encoder
  conv_channels: [32, 32]
  conv_kernel_sizes:
    - [5, 32]
    - [5, 32]
  conv_strides:
    - [2, 2]
    - [1, 1]
  poolings:
    - []
    - []
  batch_norm: True

  # optimization
  batch_size: 8
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 200
  convert_to_sgd_epoch: 200

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 200
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_encoder: 0.2
  dropout_decoder: 0
  weight_decay: 0
  init_dec_state_with_enc_state: True
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  weight_decay: 1e-5
  scheduled_sampling_prob: 0.4
  scheduled_sampling_ramp_max_step: 100000
  label_smoothing_prob: 0
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 5
  decay_rate: 0.5
  decay_patient_epoch: 5
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 5
  print_step: 100

  # MTL
  ctc_loss_weight: 0
