param:
  # corpus
  corpus: librispeech
  label_type: character
  data_size: 100h

  # features
  feature: fbank
  input_size: 123
  splice: 1
  num_stack: 2
  num_skip: 2

  # topology
  model_type: ctc
  encoder_type: lstm
  bidirectional: True
  num_units: 320
  num_proj: 0
  num_layers: 4
  bottleneck_dim: 0

  # optimization
  batch_size: 40
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 30

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.2
  weight_decay: 0
  decay_start_epoch: 10
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 15
  not_improved_patient_epoch: 5

  logits_temperature: 1

  eval_start_epoch: 10
  print_step: 100
