param:
  # corpus
  corpus: librispeech
  label_type: character
  data_size: 100h

  # features
  feature: fbank
  save_format: numpy
  input_size: 120
  splice: 11
  num_stack: 1
  num_skip: 1

  # topology
  model_type: ctc
  encoder_type: lstm
  bidirectional: True
  num_units: 320
  num_proj: 0
  num_layers: 4
  bottleneck_dim_list: [786, 74]
  channels:
    - 32
    - 32
  kernel_sizes:
    - [41, 11]
    - [21, 11]
  strides:
    - [2, 2]
    - [2, 1]
  batch_norm: True

  # optimization
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.2
  weight_decay: 1e-5
  logits_temperature: 1
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 40
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 40
  print_step: 200
