parent: ../config/ctc/character/blstm_ctc_char_100h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 1
  num_skip: 1

  # topology
  conv_channels: [32, 32]
  conv_kernel_sizes:
    - [41, 11]
    - [21, 11]
  conv_strides:
    - [2, 2]
    - [2, 1]
  poolings: [[], []]
  batch_norm: True  ###
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 3
  subsample_list:
    - False
    - False
    - False
  fc_list: [896, 74]

  # optimization
  batch_size: 20

  # annealing
  print_step: 200
