param:
  # corpus
  corpus: librispeech
  label_type: character
  data_size: 100h

  # features
  feature: fbank
  save_format: numpy
  input_channel: 40
  use_delta: True
  use_double_delta: True
  splice: 5
  num_stack: 2
  num_skip: 2

  # topology
  model_type: ctc
  encoder_type: cnn
  bidirectional: False
  num_units: 0
  num_proj: 0
  num_layers: 0
  subsample_list: False
  fc_list: [1024, 1024]
  conv_channels: [96, 96, 96, 192, 192, 192, 192, 384, 384, 384, 384]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
  batch_norm: True

  # optimization
  batch_size: 20
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 100

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.2
  weight_decay: 1e-5
  logits_temperature: 1
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 40
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 40
  print_step: 200
