parent: ../config/ctc/character/blstm_ctc_char_100h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 1
  num_skip: 1

  # topology
  conv_channels: [96, 96, 96, 192, 192, 192, 192, 384, 384, 384, 384]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
  activation: relu
  batch_norm: True
  encoder_num_layers: 0
  subsample_list:
    - False
  fc_list: [1024, 1024]

  # optimization
  batch_size: 20

  # annealing
  print_step: 200
