parent: ../config/attention/word/att_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: kanji
  num_classes: 2888

  # features
  num_stack: 1
  num_skip: 1

  # topology
  encoder_num_layers: 4
  subsample_list:
    - True
    - True
    - False
    - False
  subsample_type: drop
  embedding_dim: 64

  # optimization
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3

  # regularization
  scheduled_sampling_ramp_max_step: 400000

  # annealing
  print_step: 1000
