param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  corpus: csj
  label_type: kanji
  data_size: subset

  # features
  feature: fbank
  save_format: numpy
  input_channel: 80
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 1
  num_skip: 1

  # topology
  model_type: attention
  encoder_type: lstm
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  decoder_residual: False
  decoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False
  subsample_type: drop
  attention_type: location
  attention_dim: 128
  decoder_type: lstm
  decoder_num_units: 320
  decoder_num_layers: 1
  embedding_dim: 64
  attention_conv_num_channels: 10
  attention_conv_width: 201

  # optimization
  batch_size: 16
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 50

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_encoder: 0.2
  dropout_decoder: 0.1
  weight_decay: 1e-6
  init_dec_state: final
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  coverage_weight: 0
  scheduled_sampling_prob: 0.2
  scheduled_sampling_ramp_max_step: 800000
  label_smoothing_prob: 0.2
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 10
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 10
  print_step: 2000

  # MTL
  ctc_loss_weight: 0
