parent: ../config/attention/character/att_blstm_kanji_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  encoder_type: cnn
  conv_channels: [64, 64, 64, 128, 128, 128, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - []
    - [2, 2]
    - []
    - []
    - [2, 2]
    - []
    - []
    - [2, 2]
  activation: relu
  batch_norm: True
  encoder_num_layers: 0
  subsample_list:
    - False

  # optimization
  batch_size: 16
  optimizer: adam
  learning_rate: 1e-3

  # regularization
  scheduled_sampling_ramp_max_step: 800000

  # annealing
  print_step: 2000
