### topology
n_stacks: 1
n_skips: 1
max_n_frames: 2000
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
subsample: "1_2_2_1_1"
enc_type: conv_blstm
enc_n_units: 512
enc_n_projs: 0
enc_n_layers: 5
enc_nin: false
subsample_type: drop
attn_type: location
attn_dim: 512
attn_n_heads: 1
dec_type: lstm
dec_n_units: 1024
dec_n_projs: 0
dec_n_layers: 1
dec_bottleneck_dim: 1024
emb_dim: 512
tie_embedding: false
ctc_fc_list: ""
### optimization
batch_size: 20
optimizer: adam
learning_rate: 1e-3
n_epochs: 25
convert_to_sgd_epoch: 20
print_step: 100
metric: edit_distance
decay_type: epoch
decay_start_epoch: 10
decay_rate: 0.85
decay_patient_n_epochs: 0
sort_stop_epoch: 100
not_improved_patient_n_epochs: 5
eval_start_epoch: 1
warmup_start_learning_rate: 1e-4
warmup_n_steps: 4000
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.4
dropout_dec: 0.4
dropout_emb: 0.4
dropout_att: 0.0
weight_decay: 1e-6
ss_prob: 0.2
ss_type: constant
lsm_prob: 0.1
focal_loss_weight: 0.0
adaptive_softmax: false
# SpecAugment
freq_width: 27
n_freq_masks: 0
time_width: 70
n_time_masks: 0
time_width_upper: 1.0
### MTL
ctc_weight: 0.2
ctc_lsm_prob: 0.1
bwd_weight: 0.0
mtl_per_batch: false
task_specific_layer: false
### LM integration
lm_fusion_type: cold
lm_fusion: ''
lm_init: ''
lmobj_weight: 0.0
share_lm_softmax: false
