parent: ../config/ctc/blstm_ctc.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  encoder_dense_residual: True

  # optimization
  batch_size: 64
  convert_to_sgd_epoch: 20

  # annealing
  print_step: 10
