param:
  # framework
  backend: pytorch

  # corpus
  corpus: switchboard
  label_type: character

  # features
  feature: fbank
  tool: htk
  input_freq: 80
  use_delta: False
  use_double_delta: False
  input_channel: 1
  splice: 1
  num_stack: 1
  num_skip: 1
  max_frame_num: 2000
  min_frame_num: 40
  dynamic_batching: True

  # topology
  model_type: attention
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  decoder_residual: False
  decoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 4
  subsample_list:
    - False
    - True
    - True
    - False
  subsample_type: drop
  bridge_layer: False
  attention_type: location
  attention_dim: 128
  decoder_type: lstm
  decoder_num_units: 320
  decoder_num_layers: 1
  embedding_dim: 32
  attention_conv_num_channels: 10
  attention_conv_width: 201
  decoding_order: bahdanau
  bottleneck_dim: 320
  num_heads: 1

  # optimization
  batch_size: 50
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 25
  convert_to_sgd_epoch: 20

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True
  char_init: False
  # char_init: /n/sd8/inaguma/result/swbd/pytorch/ctc/character/blstm320H4L_drop4_adam_lr1e-3_dropen0.2_input80

  # regularization
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_input: 0
  dropout_encoder: 0.2
  dropout_decoder: 0.2
  dropout_embedding: 0.2
  weight_decay: 1e-6
  init_dec_state: zero
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  coverage_weight: 0
  scheduled_sampling_prob: 0.2
  scheduled_sampling_max_step: 50000
  label_smoothing_prob: 0.1
  weight_noise_std: 0

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 10
  decay_rate: 0.95
  decay_patient_epoch: 0
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5
  print_step: 200

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0
