parent: ./conf/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 1
  num_skip: 1
  min_frame_num: 50

  # topology
  encoder_type: cnn
  conv_channels: [128, 128, 128, 128, 256, 256, 256, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  conv_strides:
    - [1, 2]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - [3, 1]
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  activation: prelu
  batch_norm: True
  encoder_num_layers: 0
  subsample_list:
    - False

  # optimization
  batch_size: 10
  optimizer: adam
  learning_rate: 1e-3

  # regularization
  init_dec_state: zero
  scheduled_sampling_ramp_max_step: 1200000

  # annealing
  print_step: 3000
