parent: ./conf/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  decoder_residual: True
  decoder_num_layers: 4

  # optimization
  batch_size: 64

  # regularization
  scheduled_sampling_ramp_max_step: 250000

  # annealing
  print_step: 1000
