param:
  # features
  input_type: speech
  num_splice: 1
  num_stack: 1
  num_skip: 1
  max_num_frames: 2000
  min_num_frames: 40
  dynamic_batching: True

  # topology
  conv_in_channel: 1
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  conv_poolings: []
  conv_batch_norm: False
  enc_type: blstm
  enc_num_units: 320
  enc_num_projs: 0
  enc_num_layers: 5
  enc_residual: False
  subsample:
    - True
    - True
    - False
    - False
    - False
  subsample_type: drop
  att_type: location
  att_dim: 128
  att_conv_num_channels: 10
  att_conv_width: 201
  att_num_heads: 1
  att_sharpening_factor: 1.0
  att_sigmoid_smoothing: False
  bridge_layer: False
  dec_type: lstm
  dec_num_units: 320
  dec_num_projs: 0
  dec_num_layers: 1
  dec_residual: False
  emb_dim: 320
  ctc_fc_list: []

  # optimization
  batch_size: 50
  optimizer: adam
  learning_rate: 1e-3
  num_epochs: 25
  convert_to_sgd_epoch: 20
  print_step: 200

  # initialization
  param_init: 0.1
  param_init_dist: uniform
  rec_weight_orthogonal: False
  pretrained_model: False

  # regularization
  clip_grad_norm: 5.0
  clip_activation_enc: 50.0
  clip_activation_dec: 50.0
  dropout_in: 0.0
  dropout_enc: 0.2
  dropout_dec: 0.2
  dropout_emb: 0.2
  weight_decay: 1e-6
  logits_temp: 1.0
  ss_prob: 0.2
  lsm_prob: 0.1
  lsm_type: uniform

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 10
  decay_rate: 0.9
  decay_patient_epoch: 0
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5

  # MTL
  ctc_weight: 1.0
