### topology
n_stacks: 1
n_skips: 1
max_n_frames: 2000
conv_in_channel: 1
conv_channels: "256"
conv_kernel_sizes: "(3,3)"
conv_strides: "(2,2)"
conv_poolings: "(1,1)"
conv_batch_norm: false
enc_type: conv_transformer
dec_type: transformer
enc_n_layers: 12
dec_n_layers: 6
transformer_attn_type: scaled_dot
pe_type: add
d_model: 256
d_ff: 2048
transformer_attn_n_heads: 4
tie_embedding: false
ctc_fc_list: "512"
### optimization
batch_size: 32
optimizer: adam
n_epochs: 100
convert_to_sgd_epoch: 100
print_step: 200
metric: ppl
lr_factor: 10.0
early_stop_patient_n_epochs: 5
sort_stop_epoch: 100
eval_start_epoch: 10
warmup_n_steps: 25000
accum_grad_n_tokens: 0
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.1
dropout_dec: 0.1
dropout_emb: 0.1
dropout_att: 0.0
weight_decay: 1e-6
lsm_prob: 0.1
focal_loss_weight: 0.0
adaptive_softmax: false
### MTL
ctc_weight: 0.0
ctc_lsm_prob: 0.1
bwd_weight: 0.0
mtl_per_batch: false
task_specific_layer: false
