parent: ../config/ctc/blstm_ctc_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 1
  num_skip: 1
  
  # topology
  model_type: ctc
  encoder_type: lstm
  conv_channels: [32, 32]
  conv_kernel_sizes:
    - [41, 11]
    - [21, 11]
  conv_strides:
    - [2, 2]
    - [2, 1]
  poolings:
    - []
    - []
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  fc_list: [896, 74]

  # optimization
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3
  convert_to_sgd_epoch: 100

  # annealing
  print_step: 20
