parent: ../config/ctc/character/blstm_ctc_char_100h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  data_size: 960h

  # topology
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 6
  subsample_list:
    - False
    - False
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 64
  num_epoch: 40
  convert_to_sgd_epoch: 30

  # annealing
  print_step: 1000
