param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  corpus: switchboard
  data_size: 300h
  label_type: character

  # features
  feature: fbank
  tool: htk
  input_channel: 40
  use_delta: True
  use_double_delta: True
  splice: 1
  num_stack: 2
  num_skip: 2
  dynamic_batching: True

  # topology
  model_type: ctc
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  subsample_type: drop
  fc_list: []

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 30
  convert_to_sgd_epoch: 20
  pretrain_stage: False

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True
  char_init: False

  # regularization
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout_input: 0
  dropout_encoder: 0.25
  weight_decay: 1e-6
  logits_temperature: 1
  label_smoothing_prob: 0
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 5
  decay_rate: 0.75
  decay_patient_epoch: 1
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5
  print_step: 200
