parent: ../config/hierarchical_attention/att_word_freq5_att_kanji_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: pos
  label_type_sub: word_freq5
  data_size: subset
  num_classes: 16
  num_classes_sub: 12588

  # topology
  encoder_num_layers: 6
  encoder_num_layers_sub: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
    - False
  embedding_dim: 8
  embedding_dim_sub: 128

  # optimization
  batch_size: 32

  # regularization
  scheduled_sampling_ramp_max_step: 400000

  # annealing
  print_step: 1000

  # MTL
  main_loss_weight: 0.2
  ctc_loss_weight_sub: 0
  curriculum_training: False
