parent: ../config/attention/word/att_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: pos
  data_size: subset
  num_classes: 16

  # topology
  embedding_dim: 8

  # optimization
  batch_size: 64

  # regularization
  scheduled_sampling_ramp_max_step: 200000

  # annealing
  print_step: 500
