parent: ../config/attention/character/att_char_100h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  corpus: librispeech
  label_type: word_freq5
  data_size: 100h

  # topology
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  embedding_dim: 128

  # optimization
  batch_size: 64
  pretrain_stage: False

  # initialization
  char_init: False

  # regularization
  scheduled_sampling_ramp_max_step: 300000

  # annealing
  print_step: 100
