parent: ./conf/attention/word/att_blstm_word5_subset.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: fullset

  # topology
  encoder_num_layers: 5
  subsample_list:
    - False
    - True
    - True
    - False
    - False
  decoding_order: attend_generate_update
  bottleneck_dim: 256
  num_heads: 1

  # optimization
  batch_size: 40

  # initialization
  # char_init: False
  char_init: /n/sd8/inaguma/result/csj/pytorch/ctc/kanji_wb/fullset/blstm320H5L_drop4_fc_256_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0
