parent: ./conf/attention/word/att_blstm_word_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - False
    - False
  decoding_order: attend_generate_update
  num_heads: 1

  # optimization
  batch_size: 40

  # initialization
  char_init: False

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0
