parent: ./conf/attention/word/word_blstm_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - True
    - False
  decoding_order: bahdanau
  num_heads: 1

  # optimization
  batch_size: 60

  # initialization
  pretrained_model_path: False

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0

  # RNNLM fusion
  rnnlm_fusion_type: False
  rnnlm_path: False
  rnnlm_weight: 0
