parent: ./conf/attention/word/word_blstm_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - True
    - False
  decoding_order: bahdanau
  num_heads: 1

  # optimization
  batch_size: 60

  # initialization
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/character_wb/all/blstm320H5L_drop12_fc_320_adam_lr1e-3_dropen0.2_input80
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/phone_wb/all/blstm320H5L_drop12_fc_320_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0

  # RNNLM fusion
  rnnlm_fusion_type: False
  rnnlm_path: False
  rnnlm_weight: 0
