param:
  # framework
  backend: pytorch

  # corpus
  corpus: csj
  data_size: aps_other
  label_type: word
  label_type_sub: word

  # features
  input_type: speech
  feature: fbank
  tool: htk
  input_freq: 80
  use_delta: False
  use_double_delta: False
  input_channel: 1
  splice: 1
  num_stack: 1
  num_skip: 1
  max_frame_num: 2000
  min_frame_num: 40
  dynamic_batching: True

  # topology
  model_type: nested_attention
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  decoder_residual: False
  decoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  encoder_num_layers_sub: 5
  subsample_list:
    - True
    - True
    - False
    - True
    - False
  subsample_type: drop
  bridge_layer: False
  attention_type: location
  attention_dim: 128
  decoder_type: lstm
  decoder_num_units: 320
  decoder_num_layers: 1
  decoder_num_units_sub: 320
  decoder_num_layers_sub: 1
  embedding_dim: 128
  embedding_dim_sub: 128
  attention_conv_num_channels: 10
  attention_conv_width: 201
  decoding_order: bahdanau
  bottleneck_dim: 320
  bottleneck_dim_sub: 320
  backward_sub: True
  num_heads: 1
  num_heads_sub: 1

  # optimization
  batch_size: 40
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 25
  convert_to_sgd_epoch: 20

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/character_wb/aps_other/blstm320H4L_drop4_fc_320_adam_lr1e-3_dropen0.2_input80

  # regularization
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_input: 0
  dropout_encoder: 0.2
  dropout_decoder: 0.2
  dropout_embedding: 0.2
  weight_decay: 1e-6
  init_dec_state: zero
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  coverage_weight: 0
  scheduled_sampling_prob: 0.2
  scheduled_sampling_max_step: 50000
  label_smoothing_prob: 0.1
  weight_noise_std: 0

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 10
  decay_rate: 0.9
  decay_patient_epoch: 0
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5
  print_step: 200

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
  ctc_loss_weight_sub: 0

  # W2C attention
  usage_dec_sub: all
  logits_injection: False
  num_heads_dec: 1
  dec_attention_type: content

  # regularization
  dec_attend_temperature: 1
  dec_sigmoid_smoothing: True
  att_reg_weight: 0
  relax_context_vec_dec: False
  gating: False
