parent: ../config/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  encoder_num_proj: 320
  encoder_num_layers: 5

  # optimization
  batch_size: 64

  # regularization
  scheduled_sampling_ramp_max_step: 200000

  # annealing
  print_step: 500
