parent: ../config/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  data_size: fullset

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - True
    - False
    - False
  decoder_num_layers: 1

  # optimization
  batch_size: 128

  # regularization
  scheduled_sampling_ramp_max_step: 250000

  # annealing
  print_step: 1000
