parent: ../config/attention/word/att_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  data_size: fullset
  num_classes: 23178

  # topology
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
  decoder_num_layers: 1

  # optimization
  batch_size: 64

  # regularization
  scheduled_sampling_ramp_max_step: 300000

  # annealing
  print_step: 1000
