parent: ./conf/modular/p2w_blstm_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  corpus: csj
  data_size: aps_other
  vocab: False
  label_type_in: phone
  label_type_in_finetune: phone_a2p_attention_beam1
  # label_type_in_finetune: phone_a2p_ctc_beam1
  label_type: word10k

  # topology
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 60
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 25
  convert_to_sgd_epoch: 20

  # initialization
  pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/attention/word10k/aps_other/blstm320H4L_lstm320H1L_adam_lr1e-3_location_dropen0.2de0.2emb0.2_ss0.2_ls0.1_input32_bahdanau_sc_p2w

  # regularization
  scheduled_sampling_max_step: 50000

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 10
  decay_rate: 0.9
  decay_patient_epoch: 0
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 1
  print_step: 200
