parent: ./conf/modular/p2w_blstm_att_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all
  vocab: False
  # vocab: aps_other

  # topology
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 50

  # initialization
  pretrained_model_path: False

  # regularization
  scheduled_sampling_max_step: 100000

  # annealing
  print_step: 400
