param:
  # framework
  backend: pytorch

  # corpus
  corpus: csj
  data_size: subset
  label_type: word5
  label_type_sub: kanji_wb

  # features
  feature: fbank
  tool: htk
  input_channel: 80
  use_delta: False
  use_double_delta: False
  splice: 1
  num_stack: 1
  num_skip: 1
  min_frame_num: 40
  dynamic_batching: True

  # topology
  model_type: nested_attention
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  decoder_residual: False
  decoder_dense_residual: False
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  encoder_num_layers_sub: 5
  subsample_list:
    - True
    - True
    - True
    - False
    - False
  subsample_type: drop
  bridge_layer: True
  attention_type: location
  attention_dim: 128
  decoder_type: lstm
  decoder_num_units: 320
  decoder_num_layers: 1
  decoder_num_units_sub: 320
  decoder_num_layers_sub: 1
  embedding_dim: 128
  embedding_dim_sub: 64
  attention_conv_num_channels: 10
  attention_conv_width: 201
  decoding_order: attend_generate_update
  # decoding_order: conditional
  bottleneck_dim: 256
  bottleneck_dim_sub: 256
  num_heads: 1
  num_heads_sub: 1

  # optimization
  batch_size: 64
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 30
  convert_to_sgd_epoch: 20
  pretrain_stage: False

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True
  # char_init: False
  char_init: /n/sd8/inaguma/result/csj/pytorch/ctc/kanji_wb/subset/blstm320H5L_drop4_fc_256_adam_lr1e-3_dropen0.2_input80

  # regularization
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_input: 0
  dropout_encoder: 0.2
  dropout_decoder: 0.2
  dropout_embedding: 0.2
  weight_decay: 1e-6
  init_dec_state: first
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  coverage_weight: 0
  scheduled_sampling_prob: 0.2
  scheduled_sampling_ramp_max_step: 50000
  label_smoothing_prob: 0.1
  weight_noise_std: 0

  # annealing
  decay_start_epoch: 5
  decay_rate: 0.8
  decay_patient_epoch: 1
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 5
  print_step: 200

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
  ctc_loss_weight_sub: 0

  # W2C attention
  usage_dec_sub: update_decoder
  # usage_dec_sub: all
  # usage_dec_sub: no_use

  # regularization
  dec_out_sub_attend_temperature: 1
  dec_out_sub_sigmoid_smoothing: True
  attention_regularization: True

  # gating mechanism
  # gating_mechanism: no_gate
  gating_mechanism: scalar
  # gating_mechanism: elementwise
