parent: ./conf/ctc/ctc_phone61.yml
param:
  # framework
  backend: pytorch

  # topology
  encoder_type: cnn
  conv_channels: [128, 128, 128, 128, 256, 256, 256, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - [3, 1]
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  # activation: relu
  activation: prelu
  # activation: hard_tanh
  # activation: maxout
  batch_norm: True
  # batch_norm: False
  encoder_num_layers: 0
  subsample_list:
    - False
  fc_list: [1024, 1024, 1024]

  # optimization
  batch_size: 10
  optimizer: adam
  learning_rate: 1e-3
  convert_to_sgd_epoch: 50

  # annealing
  print_step: 50
