parent: ./conf/attention/bgru_att_phone61.yml
param:
  # topology
  conv_in_channel: 1
  conv_channels: [128, 128, 128, 128, 256, 256, 256, 256, 256, 256]
  conv_kernel_sizes:
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
    - [3, 5]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - [3, 1]
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
    - []
  conv_batch_norm: True
  enc_type: cnn
  enc_bidirectional: True
  enc_num_units: 0
  enc_num_projs: 0
  enc_num_layers: 0
  enc_residual: False
  subsample:
    - False
  ctc_fc_list: [1024, 1024, 1024]

  # optimization
  batch_size: 10
  optimizer: adam
  learning_rate: 1e-3
  convert_to_sgd_epoch: 50
  print_step: 50
