parent: ./conf/attention/bgru_att_phone61.yml
param:
  # topology
  conv_in_channel: 1
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  conv_batch_norm: True
  enc_type: gru
  enc_bidirectional: True
  enc_num_units: 320
  enc_num_projs: 0
  enc_num_layers: 5
  enc_residual: False
  subsample:
    - False
    - False
    - False
    - False
    - False
  ctc_fc_list: []

  # optimization
  batch_size: 16
  print_step: 20
