parent: ./conf/modular/p2w_blstm_att.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: swbd_fisher
  vocab: False
  # vocab: swbd

  # topology
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False
  decoding_order: bahdanau
  num_heads: 1

  # optimization
  batch_size: 60

  # initialization
  pretrained_model_path: False

  # regularization
  scheduled_sampling_max_step: 500000

  # annealing
  print_step: 2000
