parent: ../config/ctc/character/blstm_ctc_char_300h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: word_freq5

  # topology
  encoder_num_units: 320
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 32

  # annealing
  print_step: 2000
