# topology
lm_type: gated_conv_small
emb_dim: 300
tie_embedding: false
# optimization
batch_size: 64
bptt: 100
optimizer: nesterov
n_epochs: 40
convert_to_sgd_epoch: 40
print_step: 50
lr: 1.0
lr_decay_start_epoch: 10
lr_decay_rate: 0.9
lr_decay_patient_n_epochs: 0
lr_decay_type: always
stop_patient_n_epochs: 10
eval_start_epoch: 1
# initialization
param_init: 0.05
# regularization
clip_grad_norm: 0.1
dropout_in: 0.2
dropout_hidden: 0.5
dropout_out: 0.0
weight_decay: 1e-6
lsm_prob: 0.1
backward: false
adaptive_softmax: false
