### topology
n_stacks: 3
n_skips: 3
max_n_frames: 2000
conv_channels: "32_32"
conv_kernel_sizes: "(3,3)_(3,3)"
conv_strides: "(1,1)_(1,1)"
conv_poolings: "(2,2)_(2,2)"
conv_batch_norm: false
subsample: "1_1_1_1_1"
enc_type: lstm
enc_n_units: 1024
enc_n_projs: 0
enc_n_layers: 5
subsample_type: drop
dec_type: lstm
# ctc_fc_list: "512"
ctc_fc_list: ""
### optimization
batch_size: 50
optimizer: adam
n_epochs: 25
convert_to_sgd_epoch: 25
print_step: 500
metric: edit_distance
lr: 1e-3
lr_decay_type: always
lr_decay_start_epoch: 10
lr_decay_rate: 0.85
lr_decay_patient_n_epochs: 0
early_stop_patient_n_epochs: 5
sort_stop_epoch: 100
eval_start_epoch: 1
warmup_start_lr: 1e-4
warmup_n_steps: 0
### initialization
param_init: 0.1
### regularization
clip_grad_norm: 5.0
dropout_in: 0.0
dropout_enc: 0.4
dropout_dec: 0.4
weight_decay: 1e-6
### MTL
ctc_weight: 1.0
ctc_lsm_prob: 0.1
