parent: ../config/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # features
  num_stack: 3
  num_skip: 3

  # topology
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False
