parent: ../config/attention/word/att_blstm_word_freq5_subset.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  decoder_num_units: 1024
  decoder_num_layers: 1

  # optimization
  batch_size: 32

  # regularization
  scheduled_sampling_ramp_max_step: 400000

  # annealing
  print_step: 1000
