parent: ../config/attention/word/att_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  decoder_residual: True
  decoder_num_layers: 4

  # optimization
  batch_size: 32

  # regularization
  scheduled_sampling_ramp_max_step: 400000

  # annealing
  print_step: 1000
