parent: ../config/attention/word/att_word_freq5_subset_baseline.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # topology
  decoder_num_layers: 2

  # optimization
  batch_size: 64

  # regularization
  scheduled_sampling_ramp_max_step: 200000

  # annealing
  print_step: 500
