parent: ./conf/hierarchical_ctc/blstm_hie_ctc_word_char_train_si284.yml
param:
  # framework
  backend: pytorch

  # topology
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  activation: relu
  batch_norm: True
  encoder_bidirectional: True
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 4
  encoder_num_layers_sub: 4
  subsample_list:
    - False
    - False
    - False
    - False
  fc_list: [256]
  fc_list_sub: []

  # optimization
  batch_size: 20

  # initialization
  char_init: False
  # char_init: /n/sd8/inaguma/result/wsj/pytorch/ctc/character/train_si284/conv_64_64_128_128_blstm256H4L_bn_adam_lr1e-3_dropen0.2_input80

  # regularization
  scheduled_sampling_max_step: 30000

  # annealing
  print_step: 200

  # MTL
  main_loss_weight: 0.5
  sub_loss_weight: 0.5
