param:
  # framework
  backend: pytorch

  # corpus
  corpus: timit
  label_type: phone61

  # features
  feature: fbank
  tool: htk
  input_freq: 41
  use_delta: True
  use_double_delta: True
  input_channel: 3
  splice: 1
  num_stack: 1
  num_skip: 1
  dynamic_batching: False

  # topology
  model_type: attention
  encoder_type: lstm
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  activation: relu
  batch_norm: False
  encoder_bidirectional: True
  encoder_residual: False
  encoder_dense_residual: False
  encoder_num_units: 256
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - True
    - True
    - False
    - False
  subsample_type: drop
  bridge_layer: True
  attention_type: location
  attention_dim: 128
  decoder_type: lstm
  decoder_residual: False
  decoder_dense_residual: False
  decoder_num_units: 256
  decoder_num_layers: 1
  embedding_dim: 32
  attention_conv_num_channels: 10
  attention_conv_width: 201
  decoding_order: attend_generate_update
  bottleneck_dim: 256
  num_heads: 1

  # optimization
  batch_size: 32
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 200
  convert_to_sgd_epoch: 20

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: True
  init_forget_gate_bias_with_one: True
  char_init: False
  # NOTE: phone_init in the case of TIMIT

  # regularization
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_input: 0.2
  dropout_encoder: 0.5
  dropout_decoder: 0.2
  dropout_embedding: 0.2
  weight_decay: 1e-6
  init_dec_state: first
  sharpening_factor: 1.0
  logits_temperature: 1.0
  sigmoid_smoothing: False
  coverage_weight: 0
  scheduled_sampling_prob: 0.2
  scheduled_sampling_max_step: 4000
  label_smoothing_prob: 0.1
  weight_noise_std: 1e-9

  # annealing
  decay_start_epoch: 10
  decay_rate: 0.9
  decay_patient_epoch: 1
  sort_stop_epoch: 200
  not_improved_patient_epoch: 20
  eval_start_epoch: 10
  print_step: 10

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0
