parent: ../config/ctc/character/blstm_ctc_char_100h.yml
param:
  # framework
  backend: pytorch
  # backend: chainer

  # corpus
  label_type: word_freq5
  data_size: 100h
  num_classes: 11735

  # topology
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - False
    - False
    - False
    - False

  # optimization
  batch_size: 40

  # annealing
  print_step: 100
