parent: ./conf/ctc/word/blstm_ctc_word_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - False
    - False
  fc_list: [320]

  # optimization
  batch_size: 40

  # initialization
  char_init: False

  # annealing
  print_step: 400
