parent: ./conf/ctc/word/word_blstm_ctc_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - True
    - False
  fc_list: [320]

  # optimization
  batch_size: 60

  # initialization
  pretrained_model_path: False
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/character_wb/all/blstm320H5L_drop12_fc_320_adam_lr1e-3_dropen0.2_input80
  # pretrained_model_path: /n/sd8/inaguma/result/csj/pytorch/ctc/phone_wb/all/blstm320H5L_drop12_fc_320_adam_lr1e-3_dropen0.2_input80

  # annealing
  print_step: 400
