parent: ./conf/ctc/word/word_blstm_ctc_aps_other.yml
param:
  # framework
  backend: pytorch

  # corpus
  data_size: all

  # topology
  encoder_num_layers: 5
  subsample_list:
    - True
    - True
    - False
    - True
    - False
  fc_list: [320]

  # optimization
  batch_size: 60

  # initialization
  pretrained_model_path: False

  # annealing
  print_step: 400
