param:
  # corpus
  corpus: csj
  label_type: word_freq5
  label_type_sub: kanji
  data_size: subset

  # features
  feature: fbank
  save_format: numpy
  input_size: 123
  splice: 1
  num_stack: 2
  num_skip: 2

  # topology
  model_type: hierarchical_ctc
  encoder_type: lstm
  bidirectional: True
  num_units: 320
  num_proj: 0
  num_layers: 6
  num_layers_sub: 4
  fc_list: []
  conv_channels: []
  conv_kernel_sizes: []
  conv_strides: []
  poolings: []
  batch_norm: False

  # optimization
  batch_size: 20
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 30

  # regularization
  parameter_init: 0.1
  clip_grad_norm: 5.0
  clip_activation: 50
  dropout: 0.2
  weight_decay: 1e-5
  logits_temperature: 1

  # annealing
  decay_start_epoch: 10
  decay_rate: 0.5
  decay_patient_epoch: 3
  sort_stop_epoch: 100
  not_improved_patient_epoch: 5
  eval_start_epoch: 10
  print_step: 2000

  # MTL
  main_loss_weight: 0.5
