parent: ./conf/ctc/word/blstm_ctc_word5_subset.yml
param:
  # framework
  backend: pytorch

  # corpus
  label_type: kanji_wb

  # topology
  encoder_type: cnn
  conv_channels: [96, 96, 96, 192, 192, 192, 192, 384, 384, 384, 384]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
    - []
    - []
    - []
    - [2,2]
  activation: relu
  batch_norm: True
  encoder_num_layers: 0
  subsample_list:
    - False

  # optimization
  batch_size: 10

  # initialization
  char_init: False

  # annealing
  print_step: 1000
