parent: ./conf/ctc/word/blstm_ctc_word5_subset.yml
param:
  # framework
  backend: pytorch

  # corpus
  label_type: kanji_wb

  # topology
  conv_channels: [64, 64, 128, 128]
  conv_kernel_sizes:
    - [3, 3]
    - [3, 3]
    - [3, 3]
    - [3, 3]
  conv_strides:
    - [1, 1]
    - [1, 1]
    - [1, 1]
    - [1, 1]
  poolings:
    - []
    - [2, 2]
    - []
    - [2, 2]
  activation: relu
  batch_norm: True
  encoder_bidirectional: True
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 4
  subsample_list:
    - False
    - False
    - False
    - False
  fc_list: [256]

  # optimization
  batch_size: 25

  # initialization
  char_init: False

  # annealing
  print_step: 400
