param:
  # topology
  rnn_type: lstm
  num_units: 1024
  num_proj: 0
  num_layers: 2
  emb_dim: 1024
  tie_weights: True
  residual: True
  backward: False

  # optimization
  batch_size: 256
  optimizer: adam
  learning_rate: 1e-3
  num_epochs: 30
  convert_to_sgd_epoch: 25
  bptt: 100
  print_step: 200

  # initialization
  param_init: 0.1
  param_init_dist: uniform
  rec_weight_orthogonal: False

  # regularization
  clip_grad_norm: 5.0
  dropout_in: 0.0
  dropout_hidden: 0.5
  dropout_out: 0.0
  dropout_emb: 0.2
  weight_decay: 1e-6

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 15
  decay_rate: 0.9
  decay_patient_epoch: 0
  sort_stop_epoch: 100
  not_improved_patient_epoch: 10
  eval_start_epoch: 1
