param:
  # framework
  backend: pytorch

  # corpus
  corpus: switchboard
  vocab: False
  label_type: word

  # features
  tool: htk
  dynamic_batching: False

  # topology
  model_type: rnnlm
  rnn_type: lstm
  bidirectional: False
  num_units: 512
  num_proj: 0
  num_layers: 2
  embedding_dim: 128
  tie_weights: False
  residual_connection: True
  backward: False

  # optimization
  batch_size: 128
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 70
  convert_to_sgd_epoch: 10

  # initialization
  parameter_init_distribution: uniform
  parameter_init: 0.1
  recurrent_weight_orthogonal: False
  init_forget_gate_bias_with_one: True

  # regularization
  clip_grad_norm: 5.0
  clip_activation_encoder: 50
  clip_activation_decoder: 50
  dropout_input: 0
  dropout_hidden: 0.5
  dropout_output: 0
  dropout_embedding: 0.2
  weight_decay: 1e-6
  label_smoothing_prob: 0
  weight_noise_std: 0

  # annealing
  decay_type: per_epoch
  decay_start_epoch: 10
  decay_rate: 0.95
  decay_patient_epoch: 0
  sort_stop_epoch: 70
  not_improved_patient_epoch: 10
  eval_start_epoch: 5
  print_step: 100
