parent: ./conf/attention/character/att_char_300h.yml
param:
  # framework
  backend: pytorch

  # corpus
  corpus: switchboard
  data_size: 300h
  label_type: word5

  # topology
  encoder_num_units: 320
  encoder_num_proj: 0
  encoder_num_layers: 5
  subsample_list:
    - False
    - True
    - True
    - False
    - False
  attention_dim: 128
  decoder_num_units: 320
  embedding_dim: 128
  decoding_order: attend_generate_update
  bottleneck_dim: 256
  num_heads: 1

  # optimization
  batch_size: 50
  optimizer: adam
  learning_rate: 1e-3
  num_epoch: 30
  convert_to_sgd_epoch: 20
  pretrain_stage: False

  # initialization
  char_init: False
  # char_init: /n/sd8/inaguma/result/swbd/pytorch/ctc/character/300h/blstm320H5L_drop4_adam_lr1e-3_dropen0.2_input120

  # MTL
  backward_loss_weight: 0
  ctc_loss_weight: 0
